### ISSUE TITLE
subprocess.mswindows does not exists in Python 3.5

### ISSUE THREAD

**Issue by FedericoCeratto** [lcosmin/cmd2#2]
The module fails to run on Linux because of subprocess.mswindows:

Traceback (most recent call last):
  File "/usr/lib/python3.5/runpy.py", line 184, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/lib/python3/dist-packages/cmd2.py", line 181, in <module>
    if subprocess.mswindows:
AttributeError: module 'subprocess' has no attribute 'mswindows'

Original bug report: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=812072

**Comment by lcosmin** [comment]
This fork is outdated and unmaintained. See here, I think this is what you're looking for: https://bitbucket.org/catherinedevlin/cmd2
